### ISSUE TITLE
Task: Tissue-Generation

### ISSUE THREAD

**Issue by kaitj** [kaitj/nhp-dwiproc#28]
### Description

Mrtrix provides a command to generate 5-tissue type images for use downstream - however, the currently implemented algorithms do not work for NHP brains. Long term will want to adapt them for NHP to be able to generate these images directly in the preprocessing workflow. In the short term, can add a flag to query for 5tt images from the bids2table (assuming that it was created separately) and provide an example script that shows how to create these files (will include some description of each file used and why).

### Tasks

- [ ] Add flag to search for and use 5tt image
- [ ] Create example script to include in documentation for generating 5tt images
- [ ] Adapt 5tt workflow for NHP brains

### Freeform Notes

* Could potentially adapt script directly into workflow if assuming a common anatomical `freesurfer` pipeline.
  * Need to gauge how tissue maps are created and named more broadly in the NHP field before deciding on script inclusion.
